// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUl0LEuNBkHtSQ7mp_8RtO6re0pMAM2h4',
    appId: '1:59039691626:web:8ffaa03e98ac29f958eb13',
    messagingSenderId: '59039691626',
    projectId: 'strings-social-media',
    authDomain: 'strings-social-media.firebaseapp.com',
    storageBucket: 'strings-social-media.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa2bLr0SrR-02aAyD3Rrkm8JPKNPrQTSg',
    appId: '1:59039691626:android:d67759051a2aa55d58eb13',
    messagingSenderId: '59039691626',
    projectId: 'strings-social-media',
    storageBucket: 'strings-social-media.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAMjWZc82nbwivGEGL2xxXsfEgH-SKQw4',
    appId: '1:59039691626:ios:e6f5c9fb2b9fd94158eb13',
    messagingSenderId: '59039691626',
    projectId: 'strings-social-media',
    storageBucket: 'strings-social-media.appspot.com',
    iosBundleId: 'tech.manangandhi.stringsSocialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAMjWZc82nbwivGEGL2xxXsfEgH-SKQw4',
    appId: '1:59039691626:ios:a2dd799ee8983c5058eb13',
    messagingSenderId: '59039691626',
    projectId: 'strings-social-media',
    storageBucket: 'strings-social-media.appspot.com',
    iosBundleId: 'tech.manangandhi.stringsSocialMedia.RunnerTests',
  );
}
